os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.12.0"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=1
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - JHI_E2E_HEADLESS=true

    # if JHIPSTER_LIB_BRANCH value is release, use the release from Maven
    - JHIPSTER_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHIPSTER_LIB_BRANCH=release
    # if JHIPSTER_BRANCH value is release, use the release from NPM
    - JHIPSTER_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHIPSTER_BRANCH=master

  # ----- default applications -----
  # matrix:
  #   - JHIPSTER=ngx-default PROFILE=prod PROTRACTOR=0
  #   - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod PROTRACTOR=1
  #   - JHIPSTER=ngx-gradle-fr PROFILE=prod PROTRACTOR=1
  #   - JHIPSTER=ngx-mariadb-oauth2-sass-infinispan PROTRACTOR=1
  #   - JHIPSTER=ngx-h2mem-ws-nol2
  #   - JHIPSTER=ngx-mongodb-kafka-cucumber PROTRACTOR=0
  #   - JHIPSTER=ngx-session-cassandra-fr PROTRACTOR=0
  #   - JHIPSTER=ngx-couchbase
  #   - JHIPSTER=ms-ngx-gateway-eureka
  #   - JHIPSTER=ms-ngx-gateway-consul
  #   - JHIPSTER=ms-ngx-gateway-uaa
  #   - JHIPSTER=ms-micro-eureka
  #   - JHIPSTER=ms-micro-consul
  #   - JHIPSTER=react-mysql
  #
  # ----- ngx applications -----
  # matrix:
  #   - JHIPSTER=ngx-mysql PROFILE=prod
  #   - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=ngx-sass-noi18n
  #   - JHIPSTER=ngx-websocket PROTRACTOR=0
  #   - JHIPSTER=ngx-hazelcast-cucumber
  #   - JHIPSTER=ngx-mariadb-kafka-nol2
  #   - JHIPSTER=ngx-cassandra
  #   - JHIPSTER=ngx-mongodb
  #   - JHIPSTER=ngx-oauth2
  #   - JHIPSTER=ngx-session
  #   - JHIPSTER=ngx-infinispan
  #   - JHIPSTER=ngx-couchbase
  #
  # ----- gradle applications -----
  # matrix:
  #   - JHIPSTER=gradle-ngx-mysql PROFILE=prod
  #   - JHIPSTER=gradle-ngx-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=gradle-ngx-sass-noi18n
  #   - JHIPSTER=gradle-ngx-websocket PROTRACTOR=0
  #   - JHIPSTER=gradle-ngx-hazelcast-cucumber
  #   - JHIPSTER=gradle-ngx-mariadb-kafka-nol2
  #   - JHIPSTER=gradle-ngx-cassandra
  #   - JHIPSTER=gradle-ngx-mongodb
  #   - JHIPSTER=gradle-ngx-oauth2
  #   - JHIPSTER=gradle-ngx-session
  #   - JHIPSTER=gradle-ngx-infinispan
  #   - JHIPSTER=gradle-ngx-couchbase
  #
  # ----- microservices applications -----
  # matrix:
  #   - JHIPSTER=ms-ngx-gateway-eureka
  #   - JHIPSTER=ms-ngx-gateway-eureka-oauth2
  #   - JHIPSTER=ms-ngx-gateway-consul
  #   - JHIPSTER=ms-ngx-gateway-uaa PROTRACTOR=0
  #   - JHIPSTER=ms-micro-eureka PROTRACTOR=0
  #   - JHIPSTER=ms-micro-eureka-oauth2 PROTRACTOR=0
  #   - JHIPSTER=ms-micro-consul PROTRACTOR=0
  #
  # ----- microservices applications with Gradle -----
  # matrix:
  #   - JHIPSTER=gradle-ms-ngx-gateway-eureka
  #   - JHIPSTER=gradle-ms-ngx-gateway-eureka-oauth2
  #   - JHIPSTER=gradle-ms-ngx-gateway-consul
  #   - JHIPSTER=gradle-ms-ngx-gateway-uaa PROTRACTOR=0
  #   - JHIPSTER=gradle-ms-micro-eureka PROTRACTOR=0
  #   - JHIPSTER=gradle-ms-micro-eureka-oauth2 PROTRACTOR=0
  #   - JHIPSTER=gradle-ms-micro-consul PROTRACTOR=0
  #
  # ----- React applications -----
  # matrix:
  #   - JHIPSTER=react-mysql PROFILE=prod
  #   - JHIPSTER=react-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=react-sass-noi18n
  #   - JHIPSTER=react-websocket
  #   - JHIPSTER=react-mariadb-kafka
  #   - JHIPSTER=react-cassandra
  #   - JHIPSTER=react-mongodb
  #   - JHIPSTER=react-oauth2
  #   - JHIPSTER=react-session
  #   - JHIPSTER=react-infinispan
  #   - JHIPSTER=react-couchbase
  #
  # ----- Docker applications -----
  matrix:
    - JHIPSTER=ngx-mysql PROFILE=prod PROTRACTOR=1
  
before_install:
  - docker version
install:
  - docker pull jhipster/jhipster:master
script:
  - $TRAVIS_BUILD_DIR/travis/scripts/04-tests-docker.sh
