os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.11.1"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=1
    - JHIPSTER_TRAVIS=$HOME/generator-jhipster/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

    # if JHIPSTER_LIB_BRANCH value is release, use the release from Maven
    - JHIPSTER_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHIPSTER_LIB_BRANCH=release
    # if JHIPSTER_BRANCH value is release, use the release from NPM
    - JHIPSTER_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHIPSTER_BRANCH=master

  # ----- default applications -----
  # matrix:
  #   - JHIPSTER=ngx-default PROFILE=prod PROTRACTOR=1
  #   - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod PROTRACTOR=1
  #   - JHIPSTER=ngx-gradle-fr PROFILE=prod PROTRACTOR=1
  #   - JHIPSTER=ngx-mariadb-oauth2-sass-infinispan PROTRACTOR=1
  #   - JHIPSTER=ngx-h2mem-ws-nol2
  #   - JHIPSTER=ngx-mongodb-kafka-cucumber
  #   - JHIPSTER=ngx-session-cassandra-fr
  #   - JHIPSTER=ngx-couchbase
  #   - JHIPSTER=ms-ngx-gateway-eureka
  #   - JHIPSTER=ms-ngx-gateway-consul
  #   - JHIPSTER=ms-ngx-gateway-uaa
  #   - JHIPSTER=ms-micro-eureka
  #   - JHIPSTER=ms-micro-consul
  #   - JHIPSTER=react-default
  #
  # ----- ngx applications -----
  matrix:
    - JHIPSTER=ngx-mysql PROFILE=prod
    - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod
    - JHIPSTER=ngx-sass-noi18n
    - JHIPSTER=ngx-websocket PROTRACTOR=0
    - JHIPSTER=ngx-hazelcast-cucumber
    - JHIPSTER=ngx-mariadb-kafka-nol2
    - JHIPSTER=ngx-cassandra
    - JHIPSTER=ngx-mongodb
    - JHIPSTER=ngx-oauth2
    - JHIPSTER=ngx-session
    - JHIPSTER=ngx-infinispan
    - JHIPSTER=ngx-couchbase
  
  # ----- gradle applications -----
  # matrix:
  #   - JHIPSTER=gradle-ngx-mysql PROFILE=prod
  #   - JHIPSTER=gradle-ngx-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=gradle-ngx-sass-noi18n
  #   - JHIPSTER=gradle-ngx-websocket PROTRACTOR=0
  #   - JHIPSTER=gradle-ngx-hazelcast-cucumber
  #   - JHIPSTER=gradle-ngx-mariadb-kafka-nol2
  #   - JHIPSTER=gradle-ngx-cassandra
  #   - JHIPSTER=gradle-ngx-mongodb
  #   - JHIPSTER=gradle-ngx-oauth2
  #   - JHIPSTER=gradle-ngx-session
  #   - JHIPSTER=gradle-ngx-infinispan
  #   - JHIPSTER=gradle-ngx-couchbase
  #
  # ----- microservices applications -----
  # matrix:
  #   - JHIPSTER=ms-ngx-gateway-eureka
  #   - JHIPSTER=ms-ngx-gateway-eureka-oauth2
  #   - JHIPSTER=ms-ngx-gateway-consul
  #   - JHIPSTER=ms-ngx-gateway-uaa PROTRACTOR=0
  #   - JHIPSTER=ms-micro-eureka PROTRACTOR=0
  #   - JHIPSTER=ms-micro-eureka-oauth2 PROTRACTOR=0
  #   - JHIPSTER=ms-micro-consul PROTRACTOR=0
  #
  # ----- React applications -----
  # matrix:
  #   - JHIPSTER=react-mysql PROFILE=prod PROTRACTOR=0
  #   - JHIPSTER=react-psql-es-noi18n PROFILE=prod PROTRACTOR=0
  #   - JHIPSTER=react-sass-noi18n PROTRACTOR=0
  #   - JHIPSTER=react-websocket PROTRACTOR=0
  #   - JHIPSTER=react-mariadb-kafka PROTRACTOR=0
  #   - JHIPSTER=react-cassandra PROTRACTOR=0
  #   - JHIPSTER=react-mongodb PROTRACTOR=0
  #   - JHIPSTER=react-oauth2 PROTRACTOR=0
  #   - JHIPSTER=react-session PROTRACTOR=0
  #   - JHIPSTER=react-infinispan PROTRACTOR=0
  #   - JHIPSTER=react-couchbase PROTRACTOR=0
  #
  # ----- Docker applications -----
  # matrix:
  #   - JHIPSTER=ngx-mysql PROFILE=prod PROTRACTOR=1
  #
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install with Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn -v
install:
  - $TRAVIS_BUILD_DIR/travis/scripts/00-install-jhipster.sh
  - if [[ "$JHIPSTER" == "" ]]; then
      cd "$HOME"/generator-jhipster;
      yarn test;
    fi
  # copy samples
  - cp -R "$TRAVIS_BUILD_DIR"/travis/samples/* "$JHIPSTER_SAMPLES"/
  - ls -al "$JHIPSTER_SAMPLES"/
  - if [[ $JHIPSTER == "" ]]; then exit 0; fi;
  # generate project and entities
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
  - $JHIPSTER_SCRIPTS/03-replace-version-generated-project.sh
script:
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh

# ----- Docker build
# before_install:
#   - docker version
# install:
#   - docker pull jhipster/jhipster:master
# script:
#   - $TRAVIS_BUILD_DIR/travis/scripts/04-tests-docker.sh
